### PR TITLE
fix unison notehead accidental collision with stems down

### LINKED ISSUE #210: Unison notehead accidental collision with stems down
When stems go down, it appears that two-notehead augmented unisons have overlap between accidental and the left notehead.  

Report from Joseph VanderStel

```typescript
const note_obj = new VF.StaveNote({
    "keys":["Bn/5","B#/5"],
    "duration":"h",
    "stemDirection":-1,
});
note_obj.addModifier(new VF.Accidental('n'), 0);
note_obj.addModifier(new VF.Accidental('#'), 1);
```
Screenshot 2024-06-27 at 00 54 36

### PR DESCRIPTION
**Pull request by rvilarl**
fixes #210 

Minor code fix.

Accidental padding test modified to show fix
image

### CODE REVIEW

File: tests/accidental_tests.ts [hunk 1]
```diff
@@ -163,9 +163,9 @@ function formatAccidentalSpaces(options: TestOptions): void {
       duration: '8d',
     }).addModifier(new Accidental('##'), 0),
     new StaveNote({
-      keys: ['b/4'],
+      keys: ['Bb/4','Bn/4'],
       duration: '16',
-    }).addModifier(new Accidental('b'), 0),
+    }).addModifier(new Accidental('b'), 0).addModifier(new Accidental('n'), 0),
```
Comment (mscuthbert) [inline tests/accidental_tests.ts:168]: This is great!  Thank you!  I wonder if we should start as a good habit, adding in comments that explain the purpose of each test so that in the future if they're refactored, people know what is happening.  For instance, just adding here:

```javascript
\\ test that unisons with different accidentals layout properly with stems down
```

and later for D/4:

```javascript
\\ test that unisons with different accidentals layout properly with stems up
```

this way anyone who comes along later knows that replacing `Bb/4, Bn/4` with `Ab/4, An/4` isn't an equivalent test.

File: src/stavenote.ts [hunk 2]
```diff
@@ -569,7 +569,7 @@ export class StaveNote extends StemmableNote {
       if (lastLine === undefined) {
         lastLine = line;
       } else {
-        if (Math.abs(lastLine - line) === 0.5) {
+        if (Math.abs(lastLine - line) < 1) {
```
Comment (mscuthbert) [inline src/stavenote.ts:572]: Thanks for finding this.  wow.  Maybe good to add a comment like :`< 1 means == 0.5 (second) or 0.0 (unison)`

I totally see how this would fix the problem.  I just have no clue why it worked in the first place for stems up!

**Review by mscuthbert — APPROVED** [review]
Wow!  Looks amazing to me.  Thank you so much for taking the time to find this obscure bug that I didn't know where it was!    I put in a couple of comments that, if you wanted to take, would be nice to have in a future PR to save everyone the trouble.

File: tests/accidental_tests.ts (hunk 1 above)
Comment (mscuthbert) [reply tests/accidental_tests.ts:168]: (oops, I guess it is since there's a beamed note.  :-)

File: src/stavenote.ts (hunk 2 above)
Comment (rvilarl) [reply src/stavenote.ts:572]: With stems up the notehead is always displaced to the left
